server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mas_library?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #TODO: change to false!
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SECRET_SHOP_EMAIL_USERNAME}
    password: yiogwjuyxkhaeojk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
